export enum SecretsAvailable {
  NOMBRE_USUARIO_ESTANDAR_VALIDO = "NOMBRE_USUARIO_ESTANDAR_VALIDO",
  PASSWORD_USUARIO_ESTANDAR_CORRECTO = "PASSWORD_USUARIO_ESTANDAR_CORRECTO",
  NOMBRE_USUARIO_BLOQUEADO = "NOMBRE_USUARIO_BLOQUEADO",
  PASSWORD_USUARIO_BLOQUEADO = "PASSWORD_USUARIO_BLOQUEADO",
}
